CREATE TABLE CAT_WELL_TYPE (
	WELL_TYPE_ID INT,
	WELL_TYPE TEXT,
	PRIMARY KEY(WELL_TYPE_ID)
	);

CREATE TABLE CAT_WELL_MODE (
	WELL_MODE_ID INT,
	WELL_MODE TEXT,
	PRIMARY KEY(WELL_MODE_ID)
	);

CREATE TABLE CAT_OPERATOR (
	OPERATOR_ID INTEGER PRIMARY KEY,
	OPERATOR_NAME TEXT
	);

CREATE TABLE WELL_HDR (
	WELL_ID INTEGER,
	X NUMERIC(15, 13),
	Y NUMERIC(15, 13),
	UTM INT,
	WELL_NAME_ORIGINAL TEXT,
	WELL_NAME TEXT,
	WELL_NUMBER TEXT,
	OPERATOR_ID INT REFERENCES CAT_OPERATOR (OPERATOR_ID),
	WELL_TYPE_ID INT REFERENCES CAT_WELL_TYPE (WELL_TYPE_ID),
	WELL_MODE_ID INT REFERENCES CAT_WELL_MODE (WELL_MODE_ID),
	LICENSE_NUMBER TEXT,
	TOTAL_DEPTH numeric(8,2),
	SPUD_DATE TIMESTAMP,
	PRIMARY KEY(WELL_ID)
	);

CREATE TABLE CAT_LOG_TYPE (
	LOG_TYPE_ID INT,
	LOG_TYPE TEXT,
	PRIMARY KEY (LOG_TYPE_ID)
	);

CREATE TABLE LOG_HDR (
	LOG_ID INT, 
	LOG_NAME TEXT,
	LOG_TYPE_ID INT,
	LICENSE TEXT,
	TOTAL_DEPTH_DATE TIMESTAMP,
	X NUMERIC(10, 8),
	Y NUMERIC(10, 8),
	UTM INT,
	PRIMARY KEY (LOG_ID),
	FOREIGN KEY (LOG_TYPE_ID) REFERENCES CAT_LOG_TYPE (LOG_TYPE_ID)
	);